version: "3"

services:
  redis:
    image: redis:3-alpine
    networks:
      - internal
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE:      homestead
      MYSQL_USER:          homestead
      MYSQL_PASSWORD:      secret
    networks:
      - internal
    restart: unless-stopped

  echo:
    image: oanhnn/laravel-echo-server
    env_file:
      - .env
    environment:
      APP_URL: http://web
      LES_DB:  redis
    depends_on:
      - redis
    networks:
      - internal
    restart: unless-stopped

  app:
    build:
      dockerfile: ./.docker/application/Dockerfile
      context: .
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - internal
    restart: unless-stopped

  cron:
    build:
      dockerfile: ./.docker/application/Dockerfile
      context: .
    env_file:
      - .env
    command: /usr/sbin/crond -f -d 8
    depends_on:
      - app
    volumes:
      - .:/app
    networks:
      - internal
    restart: unless-stopped

  worker:
    build:
      dockerfile: ./.docker/application/Dockerfile
      context: .
    env_file:
      - .env
    user: www-data:www-data
    command: php /app/artisan horizon >/dev/stdout 2>/dev/stderr
    depends_on:
      - app
    volumes:
      - .:/app
    networks:
      - internal
    restart: unless-stopped

  web:
    image: nginx:stable-alpine
    volumes:
      - .:/app
      - ./.docker/webserver/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
      - external
    ports:
      - "80:80"
    depends_on:
      - app
    restart: unless-stopped

networks:
  external:
    external: true
  internal:
    driver: bridge
